
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
 
   <link rel="stylesheet" href="css/bootstrap.min.css">
    <script src="js/bootstrap.min.js"></script>
   
    <title>Update ID Request </title>
</head>
<body>

<div class="container">

<div class="col-sm-6">
<?php
$state="";
$postfix="";
$prefix="";
$id_generated="";
include "connection.php";
$a=$_GET['id'];
$selectdata=mysqli_query($con , "select * from id_request_tbl where id= $a");
$num_row=mysqli_num_rows($selectdata);
if($num_row>0)
{
	while($row=mysqli_fetch_assoc($selectdata))
	        {
		//echo $row['email'];
		        $email=$row['email'];
			      $state=$row['state'];
	        }
		   switch ($state)
		   {
			  case "bihar":
			      $prefix="BIH";
				   $rand=rand(9999999 , 1234567);
				   $postfix="XYZ";
				   $id_generated=$prefix.$rand.$postfix;
		     break;
			  
			  case "up":
			        $prefix="UTT";
				   $rand=rand(9999999 , 1234567);
				   $postfix="XYZ";
				   $id_generated=$prefix.$rand.$postfix;
		    
		     break;
			  
			  case "mp":
			       $prefix="MAD";
				   $rand=rand(9999999 , 1234567);
				   $postfix="XYZ";
				   $id_generated=$prefix.$rand.$postfix;
		    
		     break;
			  
			  
			  
			  
		   }
	     ?>
		 
		       <form method="POST">
		
		              <div class="form-group">
                      <label for="email">User_Email:</label>
                      <input type="text" class="form-control" id="email" name="email" placeholder="enter email"  value="<?php echo $email?>" required  readonly>
                      </div>
                     <div class="form-group">
                     <label for="state">User_State:</label>
                    <input type="text" class="form-control" id="state" name="state"  placeholder="enter state" value="<?php echo $state?>"  required  readonly>
					 <div class="form-group">
                     <label for="email">User ID Generated by System:</label>
                    <input type="text" class="form-control" id="voterid" name="voterid"  placeholder="enter state" value="<?php echo $id_generated?>"  required  readonly>
        
                     </div>
                    <center><button type="submit" class="btn btn-success btn-block" name="update"><b>Update User ID</b></button></center>
		</form>
		
	<?php
	
		
}
else
{
	echo "Record Not Found";
}
?>


 </div>
<div class="col-sm-6">cxvxcgfdgfdffgfgfd
</div>
</div>
</center>
</body>
</html>
<?php
if(isset($_POST['update']))
{
	$uemail=$_POST['email'];
	$ustate=$_POST['state'];
	$uid=$_POST['voterid'];
	//echo $uemail;
	//echo $uid;
	$updatedata=mysqli_query($con,"update user set user_id_generated='$uid' where email='$uemail'");
	if($updatedata)
	{
		//echo "<script> alert('successfully update')</script>";
		$deletedata=mysqli_query($con, "delete from id_request_tbl where email='$uemail'");
		if($deletedata)
		{
			echo "<script> alert('Update successfull and Deleted')</script>";
			 echo "<script>window.open('rqstddtafrID.php','_self')</script>";
		}
	}
	else{
		echo "<script>alert('something is wrong')</script>";
	}
}


?>